apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-rag-demo
  namespace: enterprise-rag
  labels:
    app: enterprise-rag-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-rag-demo
  template:
    metadata:
      labels:
        app: enterprise-rag-demo
    spec:
      containers:
        - name: enterprise-rag-demo
          image: ghcr.io/fanslin/enterprise-rag-demo:sha-1030f9ae76fbab3a1744bb4e0d65c2727e7e86c9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: APP_RAG_TOP_K
              value: "4"
            - name: APP_RAG_SIMILARITY_THRESHOLD
              value: "0.0"
          readinessProbe:
            httpGet:
              path: /api/health/ai
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/health/ai
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
