apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-rag-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fanslin/enterprise-rag-demo.git
    targetRevision: main
    path: k8s/kind
  destination:
    server: https://kubernetes.default.svc
    namespace: enterprise-rag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
